// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreateChatCompletionRequest) setDefaults() {
	{
		val := float64(1)
		s.Temperature.SetTo(val)
	}
	{
		val := float64(1)
		s.TopP.SetTo(val)
	}
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
	{
		val := float64(0)
		s.PresencePenalty.SetTo(val)
	}
	{
		val := float64(0)
		s.FrequencyPenalty.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateCompletionRequest) setDefaults() {
	{
		val := int(16)
		s.MaxTokens.SetTo(val)
	}
	{
		val := float64(1)
		s.Temperature.SetTo(val)
	}
	{
		val := float64(1)
		s.TopP.SetTo(val)
	}
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
	{
		val := bool(false)
		s.Echo.SetTo(val)
	}
	{
		val := float64(0)
		s.PresencePenalty.SetTo(val)
	}
	{
		val := float64(0)
		s.FrequencyPenalty.SetTo(val)
	}
	{
		val := int(1)
		s.BestOf.SetTo(val)
	}
}
