// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateChatCompletion implements createChatCompletion operation.
//
// Creates a model response for the given chat conversation.
//
// POST /chat/completions
func (UnimplementedHandler) CreateChatCompletion(ctx context.Context, req *CreateChatCompletionRequest) (r *CreateChatCompletionResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCompletion implements createCompletion operation.
//
// Creates a completion for the provided prompt and parameters.
//
// POST /completions
func (UnimplementedHandler) CreateCompletion(ctx context.Context, req *CreateCompletionRequest) (r *CreateCompletionResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListModels implements listModels operation.
//
// Lists the currently available models.
//
// GET /models
func (UnimplementedHandler) ListModels(ctx context.Context) (r *ListModelsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// RetrieveModel implements retrieveModel operation.
//
// Retrieves a model instance.
//
// GET /models/{model}
func (UnimplementedHandler) RetrieveModel(ctx context.Context, params RetrieveModelParams) (r *Model, _ error) {
	return r, ht.ErrNotImplemented
}
