// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/ChatCompletionChoice
type ChatCompletionChoice struct {
	Index        int                                `json:"index"`
	Message      ChatCompletionResponseMessage      `json:"message"`
	FinishReason ChatCompletionChoiceFinishReason   `json:"finish_reason"`
	Logprobs     OptNilChatCompletionChoiceLogprobs `json:"logprobs"`
}

// GetIndex returns the value of Index.
func (s *ChatCompletionChoice) GetIndex() int {
	return s.Index
}

// GetMessage returns the value of Message.
func (s *ChatCompletionChoice) GetMessage() ChatCompletionResponseMessage {
	return s.Message
}

// GetFinishReason returns the value of FinishReason.
func (s *ChatCompletionChoice) GetFinishReason() ChatCompletionChoiceFinishReason {
	return s.FinishReason
}

// GetLogprobs returns the value of Logprobs.
func (s *ChatCompletionChoice) GetLogprobs() OptNilChatCompletionChoiceLogprobs {
	return s.Logprobs
}

// SetIndex sets the value of Index.
func (s *ChatCompletionChoice) SetIndex(val int) {
	s.Index = val
}

// SetMessage sets the value of Message.
func (s *ChatCompletionChoice) SetMessage(val ChatCompletionResponseMessage) {
	s.Message = val
}

// SetFinishReason sets the value of FinishReason.
func (s *ChatCompletionChoice) SetFinishReason(val ChatCompletionChoiceFinishReason) {
	s.FinishReason = val
}

// SetLogprobs sets the value of Logprobs.
func (s *ChatCompletionChoice) SetLogprobs(val OptNilChatCompletionChoiceLogprobs) {
	s.Logprobs = val
}

type ChatCompletionChoiceFinishReason string

const (
	ChatCompletionChoiceFinishReasonStop          ChatCompletionChoiceFinishReason = "stop"
	ChatCompletionChoiceFinishReasonLength        ChatCompletionChoiceFinishReason = "length"
	ChatCompletionChoiceFinishReasonToolCalls     ChatCompletionChoiceFinishReason = "tool_calls"
	ChatCompletionChoiceFinishReasonContentFilter ChatCompletionChoiceFinishReason = "content_filter"
	ChatCompletionChoiceFinishReasonFunctionCall  ChatCompletionChoiceFinishReason = "function_call"
)

// AllValues returns all ChatCompletionChoiceFinishReason values.
func (ChatCompletionChoiceFinishReason) AllValues() []ChatCompletionChoiceFinishReason {
	return []ChatCompletionChoiceFinishReason{
		ChatCompletionChoiceFinishReasonStop,
		ChatCompletionChoiceFinishReasonLength,
		ChatCompletionChoiceFinishReasonToolCalls,
		ChatCompletionChoiceFinishReasonContentFilter,
		ChatCompletionChoiceFinishReasonFunctionCall,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionChoiceFinishReason) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionChoiceFinishReasonStop:
		return []byte(s), nil
	case ChatCompletionChoiceFinishReasonLength:
		return []byte(s), nil
	case ChatCompletionChoiceFinishReasonToolCalls:
		return []byte(s), nil
	case ChatCompletionChoiceFinishReasonContentFilter:
		return []byte(s), nil
	case ChatCompletionChoiceFinishReasonFunctionCall:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionChoiceFinishReason) UnmarshalText(data []byte) error {
	switch ChatCompletionChoiceFinishReason(data) {
	case ChatCompletionChoiceFinishReasonStop:
		*s = ChatCompletionChoiceFinishReasonStop
		return nil
	case ChatCompletionChoiceFinishReasonLength:
		*s = ChatCompletionChoiceFinishReasonLength
		return nil
	case ChatCompletionChoiceFinishReasonToolCalls:
		*s = ChatCompletionChoiceFinishReasonToolCalls
		return nil
	case ChatCompletionChoiceFinishReasonContentFilter:
		*s = ChatCompletionChoiceFinishReasonContentFilter
		return nil
	case ChatCompletionChoiceFinishReasonFunctionCall:
		*s = ChatCompletionChoiceFinishReasonFunctionCall
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionChoiceLogprobs
type ChatCompletionChoiceLogprobs struct {
	Content OptNilChatCompletionTokenLogprobArray `json:"content"`
}

// GetContent returns the value of Content.
func (s *ChatCompletionChoiceLogprobs) GetContent() OptNilChatCompletionTokenLogprobArray {
	return s.Content
}

// SetContent sets the value of Content.
func (s *ChatCompletionChoiceLogprobs) SetContent(val OptNilChatCompletionTokenLogprobArray) {
	s.Content = val
}

// Ref: #/components/schemas/ChatCompletionMessageToolCall
type ChatCompletionMessageToolCall struct {
	ID       string                                `json:"id"`
	Type     ChatCompletionMessageToolCallType     `json:"type"`
	Function ChatCompletionMessageToolCallFunction `json:"function"`
}

// GetID returns the value of ID.
func (s *ChatCompletionMessageToolCall) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *ChatCompletionMessageToolCall) GetType() ChatCompletionMessageToolCallType {
	return s.Type
}

// GetFunction returns the value of Function.
func (s *ChatCompletionMessageToolCall) GetFunction() ChatCompletionMessageToolCallFunction {
	return s.Function
}

// SetID sets the value of ID.
func (s *ChatCompletionMessageToolCall) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *ChatCompletionMessageToolCall) SetType(val ChatCompletionMessageToolCallType) {
	s.Type = val
}

// SetFunction sets the value of Function.
func (s *ChatCompletionMessageToolCall) SetFunction(val ChatCompletionMessageToolCallFunction) {
	s.Function = val
}

type ChatCompletionMessageToolCallFunction struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// GetName returns the value of Name.
func (s *ChatCompletionMessageToolCallFunction) GetName() string {
	return s.Name
}

// GetArguments returns the value of Arguments.
func (s *ChatCompletionMessageToolCallFunction) GetArguments() string {
	return s.Arguments
}

// SetName sets the value of Name.
func (s *ChatCompletionMessageToolCallFunction) SetName(val string) {
	s.Name = val
}

// SetArguments sets the value of Arguments.
func (s *ChatCompletionMessageToolCallFunction) SetArguments(val string) {
	s.Arguments = val
}

type ChatCompletionMessageToolCallType string

const (
	ChatCompletionMessageToolCallTypeFunction ChatCompletionMessageToolCallType = "function"
)

// AllValues returns all ChatCompletionMessageToolCallType values.
func (ChatCompletionMessageToolCallType) AllValues() []ChatCompletionMessageToolCallType {
	return []ChatCompletionMessageToolCallType{
		ChatCompletionMessageToolCallTypeFunction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionMessageToolCallType) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionMessageToolCallTypeFunction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionMessageToolCallType) UnmarshalText(data []byte) error {
	switch ChatCompletionMessageToolCallType(data) {
	case ChatCompletionMessageToolCallTypeFunction:
		*s = ChatCompletionMessageToolCallTypeFunction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionRequestMessage
type ChatCompletionRequestMessage struct {
	Role         ChatCompletionRequestMessageRole            `json:"role"`
	Content      string                                      `json:"content"`
	Name         OptString                                   `json:"name"`
	ToolCalls    []ChatCompletionMessageToolCall             `json:"tool_calls"`
	ToolCallID   OptString                                   `json:"tool_call_id"`
	FunctionCall OptChatCompletionRequestMessageFunctionCall `json:"function_call"`
}

// GetRole returns the value of Role.
func (s *ChatCompletionRequestMessage) GetRole() ChatCompletionRequestMessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *ChatCompletionRequestMessage) GetContent() string {
	return s.Content
}

// GetName returns the value of Name.
func (s *ChatCompletionRequestMessage) GetName() OptString {
	return s.Name
}

// GetToolCalls returns the value of ToolCalls.
func (s *ChatCompletionRequestMessage) GetToolCalls() []ChatCompletionMessageToolCall {
	return s.ToolCalls
}

// GetToolCallID returns the value of ToolCallID.
func (s *ChatCompletionRequestMessage) GetToolCallID() OptString {
	return s.ToolCallID
}

// GetFunctionCall returns the value of FunctionCall.
func (s *ChatCompletionRequestMessage) GetFunctionCall() OptChatCompletionRequestMessageFunctionCall {
	return s.FunctionCall
}

// SetRole sets the value of Role.
func (s *ChatCompletionRequestMessage) SetRole(val ChatCompletionRequestMessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *ChatCompletionRequestMessage) SetContent(val string) {
	s.Content = val
}

// SetName sets the value of Name.
func (s *ChatCompletionRequestMessage) SetName(val OptString) {
	s.Name = val
}

// SetToolCalls sets the value of ToolCalls.
func (s *ChatCompletionRequestMessage) SetToolCalls(val []ChatCompletionMessageToolCall) {
	s.ToolCalls = val
}

// SetToolCallID sets the value of ToolCallID.
func (s *ChatCompletionRequestMessage) SetToolCallID(val OptString) {
	s.ToolCallID = val
}

// SetFunctionCall sets the value of FunctionCall.
func (s *ChatCompletionRequestMessage) SetFunctionCall(val OptChatCompletionRequestMessageFunctionCall) {
	s.FunctionCall = val
}

// Ref: #/components/schemas/ChatCompletionRequestMessageFunctionCall
type ChatCompletionRequestMessageFunctionCall struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// GetName returns the value of Name.
func (s *ChatCompletionRequestMessageFunctionCall) GetName() string {
	return s.Name
}

// GetArguments returns the value of Arguments.
func (s *ChatCompletionRequestMessageFunctionCall) GetArguments() string {
	return s.Arguments
}

// SetName sets the value of Name.
func (s *ChatCompletionRequestMessageFunctionCall) SetName(val string) {
	s.Name = val
}

// SetArguments sets the value of Arguments.
func (s *ChatCompletionRequestMessageFunctionCall) SetArguments(val string) {
	s.Arguments = val
}

type ChatCompletionRequestMessageRole string

const (
	ChatCompletionRequestMessageRoleSystem    ChatCompletionRequestMessageRole = "system"
	ChatCompletionRequestMessageRoleUser      ChatCompletionRequestMessageRole = "user"
	ChatCompletionRequestMessageRoleAssistant ChatCompletionRequestMessageRole = "assistant"
	ChatCompletionRequestMessageRoleTool      ChatCompletionRequestMessageRole = "tool"
	ChatCompletionRequestMessageRoleFunction  ChatCompletionRequestMessageRole = "function"
)

// AllValues returns all ChatCompletionRequestMessageRole values.
func (ChatCompletionRequestMessageRole) AllValues() []ChatCompletionRequestMessageRole {
	return []ChatCompletionRequestMessageRole{
		ChatCompletionRequestMessageRoleSystem,
		ChatCompletionRequestMessageRoleUser,
		ChatCompletionRequestMessageRoleAssistant,
		ChatCompletionRequestMessageRoleTool,
		ChatCompletionRequestMessageRoleFunction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionRequestMessageRole) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionRequestMessageRoleSystem:
		return []byte(s), nil
	case ChatCompletionRequestMessageRoleUser:
		return []byte(s), nil
	case ChatCompletionRequestMessageRoleAssistant:
		return []byte(s), nil
	case ChatCompletionRequestMessageRoleTool:
		return []byte(s), nil
	case ChatCompletionRequestMessageRoleFunction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionRequestMessageRole) UnmarshalText(data []byte) error {
	switch ChatCompletionRequestMessageRole(data) {
	case ChatCompletionRequestMessageRoleSystem:
		*s = ChatCompletionRequestMessageRoleSystem
		return nil
	case ChatCompletionRequestMessageRoleUser:
		*s = ChatCompletionRequestMessageRoleUser
		return nil
	case ChatCompletionRequestMessageRoleAssistant:
		*s = ChatCompletionRequestMessageRoleAssistant
		return nil
	case ChatCompletionRequestMessageRoleTool:
		*s = ChatCompletionRequestMessageRoleTool
		return nil
	case ChatCompletionRequestMessageRoleFunction:
		*s = ChatCompletionRequestMessageRoleFunction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionResponseMessage
type ChatCompletionResponseMessage struct {
	Role         ChatCompletionResponseMessageRole            `json:"role"`
	Content      NilString                                    `json:"content"`
	Refusal      OptNilString                                 `json:"refusal"`
	ToolCalls    []ChatCompletionMessageToolCall              `json:"tool_calls"`
	FunctionCall OptChatCompletionResponseMessageFunctionCall `json:"function_call"`
}

// GetRole returns the value of Role.
func (s *ChatCompletionResponseMessage) GetRole() ChatCompletionResponseMessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *ChatCompletionResponseMessage) GetContent() NilString {
	return s.Content
}

// GetRefusal returns the value of Refusal.
func (s *ChatCompletionResponseMessage) GetRefusal() OptNilString {
	return s.Refusal
}

// GetToolCalls returns the value of ToolCalls.
func (s *ChatCompletionResponseMessage) GetToolCalls() []ChatCompletionMessageToolCall {
	return s.ToolCalls
}

// GetFunctionCall returns the value of FunctionCall.
func (s *ChatCompletionResponseMessage) GetFunctionCall() OptChatCompletionResponseMessageFunctionCall {
	return s.FunctionCall
}

// SetRole sets the value of Role.
func (s *ChatCompletionResponseMessage) SetRole(val ChatCompletionResponseMessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *ChatCompletionResponseMessage) SetContent(val NilString) {
	s.Content = val
}

// SetRefusal sets the value of Refusal.
func (s *ChatCompletionResponseMessage) SetRefusal(val OptNilString) {
	s.Refusal = val
}

// SetToolCalls sets the value of ToolCalls.
func (s *ChatCompletionResponseMessage) SetToolCalls(val []ChatCompletionMessageToolCall) {
	s.ToolCalls = val
}

// SetFunctionCall sets the value of FunctionCall.
func (s *ChatCompletionResponseMessage) SetFunctionCall(val OptChatCompletionResponseMessageFunctionCall) {
	s.FunctionCall = val
}

// Ref: #/components/schemas/ChatCompletionResponseMessageFunctionCall
type ChatCompletionResponseMessageFunctionCall struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// GetName returns the value of Name.
func (s *ChatCompletionResponseMessageFunctionCall) GetName() string {
	return s.Name
}

// GetArguments returns the value of Arguments.
func (s *ChatCompletionResponseMessageFunctionCall) GetArguments() string {
	return s.Arguments
}

// SetName sets the value of Name.
func (s *ChatCompletionResponseMessageFunctionCall) SetName(val string) {
	s.Name = val
}

// SetArguments sets the value of Arguments.
func (s *ChatCompletionResponseMessageFunctionCall) SetArguments(val string) {
	s.Arguments = val
}

type ChatCompletionResponseMessageRole string

const (
	ChatCompletionResponseMessageRoleAssistant ChatCompletionResponseMessageRole = "assistant"
)

// AllValues returns all ChatCompletionResponseMessageRole values.
func (ChatCompletionResponseMessageRole) AllValues() []ChatCompletionResponseMessageRole {
	return []ChatCompletionResponseMessageRole{
		ChatCompletionResponseMessageRoleAssistant,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionResponseMessageRole) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionResponseMessageRoleAssistant:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionResponseMessageRole) UnmarshalText(data []byte) error {
	switch ChatCompletionResponseMessageRole(data) {
	case ChatCompletionResponseMessageRoleAssistant:
		*s = ChatCompletionResponseMessageRoleAssistant
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionTokenLogprob
type ChatCompletionTokenLogprob struct {
	Token       string                                      `json:"token"`
	Logprob     float64                                     `json:"logprob"`
	Bytes       []int                                       `json:"bytes"`
	TopLogprobs []ChatCompletionTokenLogprobTopLogprobsItem `json:"top_logprobs"`
}

// GetToken returns the value of Token.
func (s *ChatCompletionTokenLogprob) GetToken() string {
	return s.Token
}

// GetLogprob returns the value of Logprob.
func (s *ChatCompletionTokenLogprob) GetLogprob() float64 {
	return s.Logprob
}

// GetBytes returns the value of Bytes.
func (s *ChatCompletionTokenLogprob) GetBytes() []int {
	return s.Bytes
}

// GetTopLogprobs returns the value of TopLogprobs.
func (s *ChatCompletionTokenLogprob) GetTopLogprobs() []ChatCompletionTokenLogprobTopLogprobsItem {
	return s.TopLogprobs
}

// SetToken sets the value of Token.
func (s *ChatCompletionTokenLogprob) SetToken(val string) {
	s.Token = val
}

// SetLogprob sets the value of Logprob.
func (s *ChatCompletionTokenLogprob) SetLogprob(val float64) {
	s.Logprob = val
}

// SetBytes sets the value of Bytes.
func (s *ChatCompletionTokenLogprob) SetBytes(val []int) {
	s.Bytes = val
}

// SetTopLogprobs sets the value of TopLogprobs.
func (s *ChatCompletionTokenLogprob) SetTopLogprobs(val []ChatCompletionTokenLogprobTopLogprobsItem) {
	s.TopLogprobs = val
}

type ChatCompletionTokenLogprobTopLogprobsItem struct {
	Token   string  `json:"token"`
	Logprob float64 `json:"logprob"`
	Bytes   []int   `json:"bytes"`
}

// GetToken returns the value of Token.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) GetToken() string {
	return s.Token
}

// GetLogprob returns the value of Logprob.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) GetLogprob() float64 {
	return s.Logprob
}

// GetBytes returns the value of Bytes.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) GetBytes() []int {
	return s.Bytes
}

// SetToken sets the value of Token.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) SetToken(val string) {
	s.Token = val
}

// SetLogprob sets the value of Logprob.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) SetLogprob(val float64) {
	s.Logprob = val
}

// SetBytes sets the value of Bytes.
func (s *ChatCompletionTokenLogprobTopLogprobsItem) SetBytes(val []int) {
	s.Bytes = val
}

// Ref: #/components/schemas/CompletionChoice
type CompletionChoice struct {
	Index        int                            `json:"index"`
	Text         string                         `json:"text"`
	Logprobs     OptNilCompletionChoiceLogprobs `json:"logprobs"`
	FinishReason CompletionChoiceFinishReason   `json:"finish_reason"`
}

// GetIndex returns the value of Index.
func (s *CompletionChoice) GetIndex() int {
	return s.Index
}

// GetText returns the value of Text.
func (s *CompletionChoice) GetText() string {
	return s.Text
}

// GetLogprobs returns the value of Logprobs.
func (s *CompletionChoice) GetLogprobs() OptNilCompletionChoiceLogprobs {
	return s.Logprobs
}

// GetFinishReason returns the value of FinishReason.
func (s *CompletionChoice) GetFinishReason() CompletionChoiceFinishReason {
	return s.FinishReason
}

// SetIndex sets the value of Index.
func (s *CompletionChoice) SetIndex(val int) {
	s.Index = val
}

// SetText sets the value of Text.
func (s *CompletionChoice) SetText(val string) {
	s.Text = val
}

// SetLogprobs sets the value of Logprobs.
func (s *CompletionChoice) SetLogprobs(val OptNilCompletionChoiceLogprobs) {
	s.Logprobs = val
}

// SetFinishReason sets the value of FinishReason.
func (s *CompletionChoice) SetFinishReason(val CompletionChoiceFinishReason) {
	s.FinishReason = val
}

type CompletionChoiceFinishReason string

const (
	CompletionChoiceFinishReasonStop          CompletionChoiceFinishReason = "stop"
	CompletionChoiceFinishReasonLength        CompletionChoiceFinishReason = "length"
	CompletionChoiceFinishReasonContentFilter CompletionChoiceFinishReason = "content_filter"
)

// AllValues returns all CompletionChoiceFinishReason values.
func (CompletionChoiceFinishReason) AllValues() []CompletionChoiceFinishReason {
	return []CompletionChoiceFinishReason{
		CompletionChoiceFinishReasonStop,
		CompletionChoiceFinishReasonLength,
		CompletionChoiceFinishReasonContentFilter,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CompletionChoiceFinishReason) MarshalText() ([]byte, error) {
	switch s {
	case CompletionChoiceFinishReasonStop:
		return []byte(s), nil
	case CompletionChoiceFinishReasonLength:
		return []byte(s), nil
	case CompletionChoiceFinishReasonContentFilter:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CompletionChoiceFinishReason) UnmarshalText(data []byte) error {
	switch CompletionChoiceFinishReason(data) {
	case CompletionChoiceFinishReasonStop:
		*s = CompletionChoiceFinishReasonStop
		return nil
	case CompletionChoiceFinishReasonLength:
		*s = CompletionChoiceFinishReasonLength
		return nil
	case CompletionChoiceFinishReasonContentFilter:
		*s = CompletionChoiceFinishReasonContentFilter
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CompletionChoiceLogprobs
type CompletionChoiceLogprobs struct {
	Tokens        []string                                  `json:"tokens"`
	TokenLogprobs []float64                                 `json:"token_logprobs"`
	TopLogprobs   []CompletionChoiceLogprobsTopLogprobsItem `json:"top_logprobs"`
	TextOffset    []int                                     `json:"text_offset"`
}

// GetTokens returns the value of Tokens.
func (s *CompletionChoiceLogprobs) GetTokens() []string {
	return s.Tokens
}

// GetTokenLogprobs returns the value of TokenLogprobs.
func (s *CompletionChoiceLogprobs) GetTokenLogprobs() []float64 {
	return s.TokenLogprobs
}

// GetTopLogprobs returns the value of TopLogprobs.
func (s *CompletionChoiceLogprobs) GetTopLogprobs() []CompletionChoiceLogprobsTopLogprobsItem {
	return s.TopLogprobs
}

// GetTextOffset returns the value of TextOffset.
func (s *CompletionChoiceLogprobs) GetTextOffset() []int {
	return s.TextOffset
}

// SetTokens sets the value of Tokens.
func (s *CompletionChoiceLogprobs) SetTokens(val []string) {
	s.Tokens = val
}

// SetTokenLogprobs sets the value of TokenLogprobs.
func (s *CompletionChoiceLogprobs) SetTokenLogprobs(val []float64) {
	s.TokenLogprobs = val
}

// SetTopLogprobs sets the value of TopLogprobs.
func (s *CompletionChoiceLogprobs) SetTopLogprobs(val []CompletionChoiceLogprobsTopLogprobsItem) {
	s.TopLogprobs = val
}

// SetTextOffset sets the value of TextOffset.
func (s *CompletionChoiceLogprobs) SetTextOffset(val []int) {
	s.TextOffset = val
}

type CompletionChoiceLogprobsTopLogprobsItem map[string]float64

func (s *CompletionChoiceLogprobsTopLogprobsItem) init() CompletionChoiceLogprobsTopLogprobsItem {
	m := *s
	if m == nil {
		m = map[string]float64{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/CompletionTokensDetails
type CompletionTokensDetails struct {
	ReasoningTokens          OptInt `json:"reasoning_tokens"`
	AudioTokens              OptInt `json:"audio_tokens"`
	AcceptedPredictionTokens OptInt `json:"accepted_prediction_tokens"`
	RejectedPredictionTokens OptInt `json:"rejected_prediction_tokens"`
}

// GetReasoningTokens returns the value of ReasoningTokens.
func (s *CompletionTokensDetails) GetReasoningTokens() OptInt {
	return s.ReasoningTokens
}

// GetAudioTokens returns the value of AudioTokens.
func (s *CompletionTokensDetails) GetAudioTokens() OptInt {
	return s.AudioTokens
}

// GetAcceptedPredictionTokens returns the value of AcceptedPredictionTokens.
func (s *CompletionTokensDetails) GetAcceptedPredictionTokens() OptInt {
	return s.AcceptedPredictionTokens
}

// GetRejectedPredictionTokens returns the value of RejectedPredictionTokens.
func (s *CompletionTokensDetails) GetRejectedPredictionTokens() OptInt {
	return s.RejectedPredictionTokens
}

// SetReasoningTokens sets the value of ReasoningTokens.
func (s *CompletionTokensDetails) SetReasoningTokens(val OptInt) {
	s.ReasoningTokens = val
}

// SetAudioTokens sets the value of AudioTokens.
func (s *CompletionTokensDetails) SetAudioTokens(val OptInt) {
	s.AudioTokens = val
}

// SetAcceptedPredictionTokens sets the value of AcceptedPredictionTokens.
func (s *CompletionTokensDetails) SetAcceptedPredictionTokens(val OptInt) {
	s.AcceptedPredictionTokens = val
}

// SetRejectedPredictionTokens sets the value of RejectedPredictionTokens.
func (s *CompletionTokensDetails) SetRejectedPredictionTokens(val OptInt) {
	s.RejectedPredictionTokens = val
}

// Ref: #/components/schemas/CompletionUsage
type CompletionUsage struct {
	PromptTokens            int                        `json:"prompt_tokens"`
	CompletionTokens        int                        `json:"completion_tokens"`
	TotalTokens             int                        `json:"total_tokens"`
	PromptTokensDetails     OptPromptTokensDetails     `json:"prompt_tokens_details"`
	CompletionTokensDetails OptCompletionTokensDetails `json:"completion_tokens_details"`
}

// GetPromptTokens returns the value of PromptTokens.
func (s *CompletionUsage) GetPromptTokens() int {
	return s.PromptTokens
}

// GetCompletionTokens returns the value of CompletionTokens.
func (s *CompletionUsage) GetCompletionTokens() int {
	return s.CompletionTokens
}

// GetTotalTokens returns the value of TotalTokens.
func (s *CompletionUsage) GetTotalTokens() int {
	return s.TotalTokens
}

// GetPromptTokensDetails returns the value of PromptTokensDetails.
func (s *CompletionUsage) GetPromptTokensDetails() OptPromptTokensDetails {
	return s.PromptTokensDetails
}

// GetCompletionTokensDetails returns the value of CompletionTokensDetails.
func (s *CompletionUsage) GetCompletionTokensDetails() OptCompletionTokensDetails {
	return s.CompletionTokensDetails
}

// SetPromptTokens sets the value of PromptTokens.
func (s *CompletionUsage) SetPromptTokens(val int) {
	s.PromptTokens = val
}

// SetCompletionTokens sets the value of CompletionTokens.
func (s *CompletionUsage) SetCompletionTokens(val int) {
	s.CompletionTokens = val
}

// SetTotalTokens sets the value of TotalTokens.
func (s *CompletionUsage) SetTotalTokens(val int) {
	s.TotalTokens = val
}

// SetPromptTokensDetails sets the value of PromptTokensDetails.
func (s *CompletionUsage) SetPromptTokensDetails(val OptPromptTokensDetails) {
	s.PromptTokensDetails = val
}

// SetCompletionTokensDetails sets the value of CompletionTokensDetails.
func (s *CompletionUsage) SetCompletionTokensDetails(val OptCompletionTokensDetails) {
	s.CompletionTokensDetails = val
}

// Ref: #/components/schemas/CreateChatCompletionRequest
type CreateChatCompletionRequest struct {
	// ID of the model to use.
	Model    string                         `json:"model"`
	Messages []ChatCompletionRequestMessage `json:"messages"`
	// Sampling temperature.
	Temperature OptFloat64 `json:"temperature"`
	// Nucleus sampling parameter.
	TopP OptFloat64 `json:"top_p"`
	// Number of completions to generate.
	N OptInt `json:"n"`
	// Whether to stream partial progress.
	Stream OptBool `json:"stream"`
	// Stop sequences.
	Stop OptCreateChatCompletionRequestStop `json:"stop"`
	// Maximum tokens to generate.
	MaxTokens OptInt `json:"max_tokens"`
	// Maximum completion tokens to generate.
	MaxCompletionTokens OptInt                                  `json:"max_completion_tokens"`
	PresencePenalty     OptFloat64                              `json:"presence_penalty"`
	FrequencyPenalty    OptFloat64                              `json:"frequency_penalty"`
	LogitBias           OptCreateChatCompletionRequestLogitBias `json:"logit_bias"`
	// A unique identifier representing your end-user.
	User OptString `json:"user"`
	// Seed for deterministic sampling.
	Seed OptInt `json:"seed"`
}

// GetModel returns the value of Model.
func (s *CreateChatCompletionRequest) GetModel() string {
	return s.Model
}

// GetMessages returns the value of Messages.
func (s *CreateChatCompletionRequest) GetMessages() []ChatCompletionRequestMessage {
	return s.Messages
}

// GetTemperature returns the value of Temperature.
func (s *CreateChatCompletionRequest) GetTemperature() OptFloat64 {
	return s.Temperature
}

// GetTopP returns the value of TopP.
func (s *CreateChatCompletionRequest) GetTopP() OptFloat64 {
	return s.TopP
}

// GetN returns the value of N.
func (s *CreateChatCompletionRequest) GetN() OptInt {
	return s.N
}

// GetStream returns the value of Stream.
func (s *CreateChatCompletionRequest) GetStream() OptBool {
	return s.Stream
}

// GetStop returns the value of Stop.
func (s *CreateChatCompletionRequest) GetStop() OptCreateChatCompletionRequestStop {
	return s.Stop
}

// GetMaxTokens returns the value of MaxTokens.
func (s *CreateChatCompletionRequest) GetMaxTokens() OptInt {
	return s.MaxTokens
}

// GetMaxCompletionTokens returns the value of MaxCompletionTokens.
func (s *CreateChatCompletionRequest) GetMaxCompletionTokens() OptInt {
	return s.MaxCompletionTokens
}

// GetPresencePenalty returns the value of PresencePenalty.
func (s *CreateChatCompletionRequest) GetPresencePenalty() OptFloat64 {
	return s.PresencePenalty
}

// GetFrequencyPenalty returns the value of FrequencyPenalty.
func (s *CreateChatCompletionRequest) GetFrequencyPenalty() OptFloat64 {
	return s.FrequencyPenalty
}

// GetLogitBias returns the value of LogitBias.
func (s *CreateChatCompletionRequest) GetLogitBias() OptCreateChatCompletionRequestLogitBias {
	return s.LogitBias
}

// GetUser returns the value of User.
func (s *CreateChatCompletionRequest) GetUser() OptString {
	return s.User
}

// GetSeed returns the value of Seed.
func (s *CreateChatCompletionRequest) GetSeed() OptInt {
	return s.Seed
}

// SetModel sets the value of Model.
func (s *CreateChatCompletionRequest) SetModel(val string) {
	s.Model = val
}

// SetMessages sets the value of Messages.
func (s *CreateChatCompletionRequest) SetMessages(val []ChatCompletionRequestMessage) {
	s.Messages = val
}

// SetTemperature sets the value of Temperature.
func (s *CreateChatCompletionRequest) SetTemperature(val OptFloat64) {
	s.Temperature = val
}

// SetTopP sets the value of TopP.
func (s *CreateChatCompletionRequest) SetTopP(val OptFloat64) {
	s.TopP = val
}

// SetN sets the value of N.
func (s *CreateChatCompletionRequest) SetN(val OptInt) {
	s.N = val
}

// SetStream sets the value of Stream.
func (s *CreateChatCompletionRequest) SetStream(val OptBool) {
	s.Stream = val
}

// SetStop sets the value of Stop.
func (s *CreateChatCompletionRequest) SetStop(val OptCreateChatCompletionRequestStop) {
	s.Stop = val
}

// SetMaxTokens sets the value of MaxTokens.
func (s *CreateChatCompletionRequest) SetMaxTokens(val OptInt) {
	s.MaxTokens = val
}

// SetMaxCompletionTokens sets the value of MaxCompletionTokens.
func (s *CreateChatCompletionRequest) SetMaxCompletionTokens(val OptInt) {
	s.MaxCompletionTokens = val
}

// SetPresencePenalty sets the value of PresencePenalty.
func (s *CreateChatCompletionRequest) SetPresencePenalty(val OptFloat64) {
	s.PresencePenalty = val
}

// SetFrequencyPenalty sets the value of FrequencyPenalty.
func (s *CreateChatCompletionRequest) SetFrequencyPenalty(val OptFloat64) {
	s.FrequencyPenalty = val
}

// SetLogitBias sets the value of LogitBias.
func (s *CreateChatCompletionRequest) SetLogitBias(val OptCreateChatCompletionRequestLogitBias) {
	s.LogitBias = val
}

// SetUser sets the value of User.
func (s *CreateChatCompletionRequest) SetUser(val OptString) {
	s.User = val
}

// SetSeed sets the value of Seed.
func (s *CreateChatCompletionRequest) SetSeed(val OptInt) {
	s.Seed = val
}

type CreateChatCompletionRequestLogitBias map[string]int

func (s *CreateChatCompletionRequestLogitBias) init() CreateChatCompletionRequestLogitBias {
	m := *s
	if m == nil {
		m = map[string]int{}
		*s = m
	}
	return m
}

// Stop sequences.
// CreateChatCompletionRequestStop represents sum type.
type CreateChatCompletionRequestStop struct {
	Type        CreateChatCompletionRequestStopType // switch on this field
	String      string
	StringArray []string
}

// CreateChatCompletionRequestStopType is oneOf type of CreateChatCompletionRequestStop.
type CreateChatCompletionRequestStopType string

// Possible values for CreateChatCompletionRequestStopType.
const (
	StringCreateChatCompletionRequestStop      CreateChatCompletionRequestStopType = "string"
	StringArrayCreateChatCompletionRequestStop CreateChatCompletionRequestStopType = "[]string"
)

// IsString reports whether CreateChatCompletionRequestStop is string.
func (s CreateChatCompletionRequestStop) IsString() bool {
	return s.Type == StringCreateChatCompletionRequestStop
}

// IsStringArray reports whether CreateChatCompletionRequestStop is []string.
func (s CreateChatCompletionRequestStop) IsStringArray() bool {
	return s.Type == StringArrayCreateChatCompletionRequestStop
}

// SetString sets CreateChatCompletionRequestStop to string.
func (s *CreateChatCompletionRequestStop) SetString(v string) {
	s.Type = StringCreateChatCompletionRequestStop
	s.String = v
}

// GetString returns string and true boolean if CreateChatCompletionRequestStop is string.
func (s CreateChatCompletionRequestStop) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringCreateChatCompletionRequestStop returns new CreateChatCompletionRequestStop from string.
func NewStringCreateChatCompletionRequestStop(v string) CreateChatCompletionRequestStop {
	var s CreateChatCompletionRequestStop
	s.SetString(v)
	return s
}

// SetStringArray sets CreateChatCompletionRequestStop to []string.
func (s *CreateChatCompletionRequestStop) SetStringArray(v []string) {
	s.Type = StringArrayCreateChatCompletionRequestStop
	s.StringArray = v
}

// GetStringArray returns []string and true boolean if CreateChatCompletionRequestStop is []string.
func (s CreateChatCompletionRequestStop) GetStringArray() (v []string, ok bool) {
	if !s.IsStringArray() {
		return v, false
	}
	return s.StringArray, true
}

// NewStringArrayCreateChatCompletionRequestStop returns new CreateChatCompletionRequestStop from []string.
func NewStringArrayCreateChatCompletionRequestStop(v []string) CreateChatCompletionRequestStop {
	var s CreateChatCompletionRequestStop
	s.SetStringArray(v)
	return s
}

// Ref: #/components/schemas/CreateChatCompletionResponse
type CreateChatCompletionResponse struct {
	ID                string                             `json:"id"`
	Object            CreateChatCompletionResponseObject `json:"object"`
	Created           int64                              `json:"created"`
	Model             string                             `json:"model"`
	Choices           []ChatCompletionChoice             `json:"choices"`
	Usage             OptCompletionUsage                 `json:"usage"`
	SystemFingerprint OptString                          `json:"system_fingerprint"`
	ServiceTier       OptString                          `json:"service_tier"`
}

// GetID returns the value of ID.
func (s *CreateChatCompletionResponse) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *CreateChatCompletionResponse) GetObject() CreateChatCompletionResponseObject {
	return s.Object
}

// GetCreated returns the value of Created.
func (s *CreateChatCompletionResponse) GetCreated() int64 {
	return s.Created
}

// GetModel returns the value of Model.
func (s *CreateChatCompletionResponse) GetModel() string {
	return s.Model
}

// GetChoices returns the value of Choices.
func (s *CreateChatCompletionResponse) GetChoices() []ChatCompletionChoice {
	return s.Choices
}

// GetUsage returns the value of Usage.
func (s *CreateChatCompletionResponse) GetUsage() OptCompletionUsage {
	return s.Usage
}

// GetSystemFingerprint returns the value of SystemFingerprint.
func (s *CreateChatCompletionResponse) GetSystemFingerprint() OptString {
	return s.SystemFingerprint
}

// GetServiceTier returns the value of ServiceTier.
func (s *CreateChatCompletionResponse) GetServiceTier() OptString {
	return s.ServiceTier
}

// SetID sets the value of ID.
func (s *CreateChatCompletionResponse) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *CreateChatCompletionResponse) SetObject(val CreateChatCompletionResponseObject) {
	s.Object = val
}

// SetCreated sets the value of Created.
func (s *CreateChatCompletionResponse) SetCreated(val int64) {
	s.Created = val
}

// SetModel sets the value of Model.
func (s *CreateChatCompletionResponse) SetModel(val string) {
	s.Model = val
}

// SetChoices sets the value of Choices.
func (s *CreateChatCompletionResponse) SetChoices(val []ChatCompletionChoice) {
	s.Choices = val
}

// SetUsage sets the value of Usage.
func (s *CreateChatCompletionResponse) SetUsage(val OptCompletionUsage) {
	s.Usage = val
}

// SetSystemFingerprint sets the value of SystemFingerprint.
func (s *CreateChatCompletionResponse) SetSystemFingerprint(val OptString) {
	s.SystemFingerprint = val
}

// SetServiceTier sets the value of ServiceTier.
func (s *CreateChatCompletionResponse) SetServiceTier(val OptString) {
	s.ServiceTier = val
}

type CreateChatCompletionResponseObject string

const (
	CreateChatCompletionResponseObjectChatCompletion CreateChatCompletionResponseObject = "chat.completion"
)

// AllValues returns all CreateChatCompletionResponseObject values.
func (CreateChatCompletionResponseObject) AllValues() []CreateChatCompletionResponseObject {
	return []CreateChatCompletionResponseObject{
		CreateChatCompletionResponseObjectChatCompletion,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateChatCompletionResponseObject) MarshalText() ([]byte, error) {
	switch s {
	case CreateChatCompletionResponseObjectChatCompletion:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateChatCompletionResponseObject) UnmarshalText(data []byte) error {
	switch CreateChatCompletionResponseObject(data) {
	case CreateChatCompletionResponseObjectChatCompletion:
		*s = CreateChatCompletionResponseObjectChatCompletion
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CreateCompletionRequest
type CreateCompletionRequest struct {
	Model            string                              `json:"model"`
	Prompt           CreateCompletionRequestPrompt       `json:"prompt"`
	Suffix           OptNilString                        `json:"suffix"`
	MaxTokens        OptInt                              `json:"max_tokens"`
	Temperature      OptFloat64                          `json:"temperature"`
	TopP             OptFloat64                          `json:"top_p"`
	N                OptInt                              `json:"n"`
	Stream           OptBool                             `json:"stream"`
	Logprobs         OptNilInt                           `json:"logprobs"`
	Echo             OptBool                             `json:"echo"`
	Stop             OptCreateCompletionRequestStop      `json:"stop"`
	PresencePenalty  OptFloat64                          `json:"presence_penalty"`
	FrequencyPenalty OptFloat64                          `json:"frequency_penalty"`
	BestOf           OptInt                              `json:"best_of"`
	LogitBias        OptCreateCompletionRequestLogitBias `json:"logit_bias"`
	User             OptString                           `json:"user"`
	Seed             OptInt                              `json:"seed"`
}

// GetModel returns the value of Model.
func (s *CreateCompletionRequest) GetModel() string {
	return s.Model
}

// GetPrompt returns the value of Prompt.
func (s *CreateCompletionRequest) GetPrompt() CreateCompletionRequestPrompt {
	return s.Prompt
}

// GetSuffix returns the value of Suffix.
func (s *CreateCompletionRequest) GetSuffix() OptNilString {
	return s.Suffix
}

// GetMaxTokens returns the value of MaxTokens.
func (s *CreateCompletionRequest) GetMaxTokens() OptInt {
	return s.MaxTokens
}

// GetTemperature returns the value of Temperature.
func (s *CreateCompletionRequest) GetTemperature() OptFloat64 {
	return s.Temperature
}

// GetTopP returns the value of TopP.
func (s *CreateCompletionRequest) GetTopP() OptFloat64 {
	return s.TopP
}

// GetN returns the value of N.
func (s *CreateCompletionRequest) GetN() OptInt {
	return s.N
}

// GetStream returns the value of Stream.
func (s *CreateCompletionRequest) GetStream() OptBool {
	return s.Stream
}

// GetLogprobs returns the value of Logprobs.
func (s *CreateCompletionRequest) GetLogprobs() OptNilInt {
	return s.Logprobs
}

// GetEcho returns the value of Echo.
func (s *CreateCompletionRequest) GetEcho() OptBool {
	return s.Echo
}

// GetStop returns the value of Stop.
func (s *CreateCompletionRequest) GetStop() OptCreateCompletionRequestStop {
	return s.Stop
}

// GetPresencePenalty returns the value of PresencePenalty.
func (s *CreateCompletionRequest) GetPresencePenalty() OptFloat64 {
	return s.PresencePenalty
}

// GetFrequencyPenalty returns the value of FrequencyPenalty.
func (s *CreateCompletionRequest) GetFrequencyPenalty() OptFloat64 {
	return s.FrequencyPenalty
}

// GetBestOf returns the value of BestOf.
func (s *CreateCompletionRequest) GetBestOf() OptInt {
	return s.BestOf
}

// GetLogitBias returns the value of LogitBias.
func (s *CreateCompletionRequest) GetLogitBias() OptCreateCompletionRequestLogitBias {
	return s.LogitBias
}

// GetUser returns the value of User.
func (s *CreateCompletionRequest) GetUser() OptString {
	return s.User
}

// GetSeed returns the value of Seed.
func (s *CreateCompletionRequest) GetSeed() OptInt {
	return s.Seed
}

// SetModel sets the value of Model.
func (s *CreateCompletionRequest) SetModel(val string) {
	s.Model = val
}

// SetPrompt sets the value of Prompt.
func (s *CreateCompletionRequest) SetPrompt(val CreateCompletionRequestPrompt) {
	s.Prompt = val
}

// SetSuffix sets the value of Suffix.
func (s *CreateCompletionRequest) SetSuffix(val OptNilString) {
	s.Suffix = val
}

// SetMaxTokens sets the value of MaxTokens.
func (s *CreateCompletionRequest) SetMaxTokens(val OptInt) {
	s.MaxTokens = val
}

// SetTemperature sets the value of Temperature.
func (s *CreateCompletionRequest) SetTemperature(val OptFloat64) {
	s.Temperature = val
}

// SetTopP sets the value of TopP.
func (s *CreateCompletionRequest) SetTopP(val OptFloat64) {
	s.TopP = val
}

// SetN sets the value of N.
func (s *CreateCompletionRequest) SetN(val OptInt) {
	s.N = val
}

// SetStream sets the value of Stream.
func (s *CreateCompletionRequest) SetStream(val OptBool) {
	s.Stream = val
}

// SetLogprobs sets the value of Logprobs.
func (s *CreateCompletionRequest) SetLogprobs(val OptNilInt) {
	s.Logprobs = val
}

// SetEcho sets the value of Echo.
func (s *CreateCompletionRequest) SetEcho(val OptBool) {
	s.Echo = val
}

// SetStop sets the value of Stop.
func (s *CreateCompletionRequest) SetStop(val OptCreateCompletionRequestStop) {
	s.Stop = val
}

// SetPresencePenalty sets the value of PresencePenalty.
func (s *CreateCompletionRequest) SetPresencePenalty(val OptFloat64) {
	s.PresencePenalty = val
}

// SetFrequencyPenalty sets the value of FrequencyPenalty.
func (s *CreateCompletionRequest) SetFrequencyPenalty(val OptFloat64) {
	s.FrequencyPenalty = val
}

// SetBestOf sets the value of BestOf.
func (s *CreateCompletionRequest) SetBestOf(val OptInt) {
	s.BestOf = val
}

// SetLogitBias sets the value of LogitBias.
func (s *CreateCompletionRequest) SetLogitBias(val OptCreateCompletionRequestLogitBias) {
	s.LogitBias = val
}

// SetUser sets the value of User.
func (s *CreateCompletionRequest) SetUser(val OptString) {
	s.User = val
}

// SetSeed sets the value of Seed.
func (s *CreateCompletionRequest) SetSeed(val OptInt) {
	s.Seed = val
}

type CreateCompletionRequestLogitBias map[string]int

func (s *CreateCompletionRequestLogitBias) init() CreateCompletionRequestLogitBias {
	m := *s
	if m == nil {
		m = map[string]int{}
		*s = m
	}
	return m
}

// CreateCompletionRequestPrompt represents sum type.
type CreateCompletionRequestPrompt struct {
	Type        CreateCompletionRequestPromptType // switch on this field
	String      string
	StringArray []string
}

// CreateCompletionRequestPromptType is oneOf type of CreateCompletionRequestPrompt.
type CreateCompletionRequestPromptType string

// Possible values for CreateCompletionRequestPromptType.
const (
	StringCreateCompletionRequestPrompt      CreateCompletionRequestPromptType = "string"
	StringArrayCreateCompletionRequestPrompt CreateCompletionRequestPromptType = "[]string"
)

// IsString reports whether CreateCompletionRequestPrompt is string.
func (s CreateCompletionRequestPrompt) IsString() bool {
	return s.Type == StringCreateCompletionRequestPrompt
}

// IsStringArray reports whether CreateCompletionRequestPrompt is []string.
func (s CreateCompletionRequestPrompt) IsStringArray() bool {
	return s.Type == StringArrayCreateCompletionRequestPrompt
}

// SetString sets CreateCompletionRequestPrompt to string.
func (s *CreateCompletionRequestPrompt) SetString(v string) {
	s.Type = StringCreateCompletionRequestPrompt
	s.String = v
}

// GetString returns string and true boolean if CreateCompletionRequestPrompt is string.
func (s CreateCompletionRequestPrompt) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringCreateCompletionRequestPrompt returns new CreateCompletionRequestPrompt from string.
func NewStringCreateCompletionRequestPrompt(v string) CreateCompletionRequestPrompt {
	var s CreateCompletionRequestPrompt
	s.SetString(v)
	return s
}

// SetStringArray sets CreateCompletionRequestPrompt to []string.
func (s *CreateCompletionRequestPrompt) SetStringArray(v []string) {
	s.Type = StringArrayCreateCompletionRequestPrompt
	s.StringArray = v
}

// GetStringArray returns []string and true boolean if CreateCompletionRequestPrompt is []string.
func (s CreateCompletionRequestPrompt) GetStringArray() (v []string, ok bool) {
	if !s.IsStringArray() {
		return v, false
	}
	return s.StringArray, true
}

// NewStringArrayCreateCompletionRequestPrompt returns new CreateCompletionRequestPrompt from []string.
func NewStringArrayCreateCompletionRequestPrompt(v []string) CreateCompletionRequestPrompt {
	var s CreateCompletionRequestPrompt
	s.SetStringArray(v)
	return s
}

// CreateCompletionRequestStop represents sum type.
type CreateCompletionRequestStop struct {
	Type        CreateCompletionRequestStopType // switch on this field
	String      string
	StringArray []string
}

// CreateCompletionRequestStopType is oneOf type of CreateCompletionRequestStop.
type CreateCompletionRequestStopType string

// Possible values for CreateCompletionRequestStopType.
const (
	StringCreateCompletionRequestStop      CreateCompletionRequestStopType = "string"
	StringArrayCreateCompletionRequestStop CreateCompletionRequestStopType = "[]string"
)

// IsString reports whether CreateCompletionRequestStop is string.
func (s CreateCompletionRequestStop) IsString() bool {
	return s.Type == StringCreateCompletionRequestStop
}

// IsStringArray reports whether CreateCompletionRequestStop is []string.
func (s CreateCompletionRequestStop) IsStringArray() bool {
	return s.Type == StringArrayCreateCompletionRequestStop
}

// SetString sets CreateCompletionRequestStop to string.
func (s *CreateCompletionRequestStop) SetString(v string) {
	s.Type = StringCreateCompletionRequestStop
	s.String = v
}

// GetString returns string and true boolean if CreateCompletionRequestStop is string.
func (s CreateCompletionRequestStop) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringCreateCompletionRequestStop returns new CreateCompletionRequestStop from string.
func NewStringCreateCompletionRequestStop(v string) CreateCompletionRequestStop {
	var s CreateCompletionRequestStop
	s.SetString(v)
	return s
}

// SetStringArray sets CreateCompletionRequestStop to []string.
func (s *CreateCompletionRequestStop) SetStringArray(v []string) {
	s.Type = StringArrayCreateCompletionRequestStop
	s.StringArray = v
}

// GetStringArray returns []string and true boolean if CreateCompletionRequestStop is []string.
func (s CreateCompletionRequestStop) GetStringArray() (v []string, ok bool) {
	if !s.IsStringArray() {
		return v, false
	}
	return s.StringArray, true
}

// NewStringArrayCreateCompletionRequestStop returns new CreateCompletionRequestStop from []string.
func NewStringArrayCreateCompletionRequestStop(v []string) CreateCompletionRequestStop {
	var s CreateCompletionRequestStop
	s.SetStringArray(v)
	return s
}

// Ref: #/components/schemas/CreateCompletionResponse
type CreateCompletionResponse struct {
	ID                string                         `json:"id"`
	Object            CreateCompletionResponseObject `json:"object"`
	Created           int64                          `json:"created"`
	Model             string                         `json:"model"`
	Choices           []CompletionChoice             `json:"choices"`
	Usage             OptCompletionUsage             `json:"usage"`
	SystemFingerprint OptString                      `json:"system_fingerprint"`
}

// GetID returns the value of ID.
func (s *CreateCompletionResponse) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *CreateCompletionResponse) GetObject() CreateCompletionResponseObject {
	return s.Object
}

// GetCreated returns the value of Created.
func (s *CreateCompletionResponse) GetCreated() int64 {
	return s.Created
}

// GetModel returns the value of Model.
func (s *CreateCompletionResponse) GetModel() string {
	return s.Model
}

// GetChoices returns the value of Choices.
func (s *CreateCompletionResponse) GetChoices() []CompletionChoice {
	return s.Choices
}

// GetUsage returns the value of Usage.
func (s *CreateCompletionResponse) GetUsage() OptCompletionUsage {
	return s.Usage
}

// GetSystemFingerprint returns the value of SystemFingerprint.
func (s *CreateCompletionResponse) GetSystemFingerprint() OptString {
	return s.SystemFingerprint
}

// SetID sets the value of ID.
func (s *CreateCompletionResponse) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *CreateCompletionResponse) SetObject(val CreateCompletionResponseObject) {
	s.Object = val
}

// SetCreated sets the value of Created.
func (s *CreateCompletionResponse) SetCreated(val int64) {
	s.Created = val
}

// SetModel sets the value of Model.
func (s *CreateCompletionResponse) SetModel(val string) {
	s.Model = val
}

// SetChoices sets the value of Choices.
func (s *CreateCompletionResponse) SetChoices(val []CompletionChoice) {
	s.Choices = val
}

// SetUsage sets the value of Usage.
func (s *CreateCompletionResponse) SetUsage(val OptCompletionUsage) {
	s.Usage = val
}

// SetSystemFingerprint sets the value of SystemFingerprint.
func (s *CreateCompletionResponse) SetSystemFingerprint(val OptString) {
	s.SystemFingerprint = val
}

type CreateCompletionResponseObject string

const (
	CreateCompletionResponseObjectTextCompletion CreateCompletionResponseObject = "text_completion"
)

// AllValues returns all CreateCompletionResponseObject values.
func (CreateCompletionResponseObject) AllValues() []CreateCompletionResponseObject {
	return []CreateCompletionResponseObject{
		CreateCompletionResponseObjectTextCompletion,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateCompletionResponseObject) MarshalText() ([]byte, error) {
	switch s {
	case CreateCompletionResponseObjectTextCompletion:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateCompletionResponseObject) UnmarshalText(data []byte) error {
	switch CreateCompletionResponseObject(data) {
	case CreateCompletionResponseObjectTextCompletion:
		*s = CreateCompletionResponseObjectTextCompletion
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ListModelsResponse
type ListModelsResponse struct {
	Object ListModelsResponseObject `json:"object"`
	Data   []Model                  `json:"data"`
}

// GetObject returns the value of Object.
func (s *ListModelsResponse) GetObject() ListModelsResponseObject {
	return s.Object
}

// GetData returns the value of Data.
func (s *ListModelsResponse) GetData() []Model {
	return s.Data
}

// SetObject sets the value of Object.
func (s *ListModelsResponse) SetObject(val ListModelsResponseObject) {
	s.Object = val
}

// SetData sets the value of Data.
func (s *ListModelsResponse) SetData(val []Model) {
	s.Data = val
}

type ListModelsResponseObject string

const (
	ListModelsResponseObjectList ListModelsResponseObject = "list"
)

// AllValues returns all ListModelsResponseObject values.
func (ListModelsResponseObject) AllValues() []ListModelsResponseObject {
	return []ListModelsResponseObject{
		ListModelsResponseObjectList,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListModelsResponseObject) MarshalText() ([]byte, error) {
	switch s {
	case ListModelsResponseObjectList:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListModelsResponseObject) UnmarshalText(data []byte) error {
	switch ListModelsResponseObject(data) {
	case ListModelsResponseObjectList:
		*s = ListModelsResponseObjectList
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Model
type Model struct {
	// The model identifier.
	ID     string      `json:"id"`
	Object ModelObject `json:"object"`
	// Unix timestamp of when the model was created.
	Created int64 `json:"created"`
	// Organization that owns the model.
	OwnedBy string `json:"owned_by"`
}

// GetID returns the value of ID.
func (s *Model) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *Model) GetObject() ModelObject {
	return s.Object
}

// GetCreated returns the value of Created.
func (s *Model) GetCreated() int64 {
	return s.Created
}

// GetOwnedBy returns the value of OwnedBy.
func (s *Model) GetOwnedBy() string {
	return s.OwnedBy
}

// SetID sets the value of ID.
func (s *Model) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *Model) SetObject(val ModelObject) {
	s.Object = val
}

// SetCreated sets the value of Created.
func (s *Model) SetCreated(val int64) {
	s.Created = val
}

// SetOwnedBy sets the value of OwnedBy.
func (s *Model) SetOwnedBy(val string) {
	s.OwnedBy = val
}

type ModelObject string

const (
	ModelObjectModel ModelObject = "model"
)

// AllValues returns all ModelObject values.
func (ModelObject) AllValues() []ModelObject {
	return []ModelObject{
		ModelObjectModel,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ModelObject) MarshalText() ([]byte, error) {
	switch s {
	case ModelObjectModel:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ModelObject) UnmarshalText(data []byte) error {
	switch ModelObject(data) {
	case ModelObjectModel:
		*s = ModelObjectModel
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptChatCompletionRequestMessageFunctionCall returns new OptChatCompletionRequestMessageFunctionCall with value set to v.
func NewOptChatCompletionRequestMessageFunctionCall(v ChatCompletionRequestMessageFunctionCall) OptChatCompletionRequestMessageFunctionCall {
	return OptChatCompletionRequestMessageFunctionCall{
		Value: v,
		Set:   true,
	}
}

// OptChatCompletionRequestMessageFunctionCall is optional ChatCompletionRequestMessageFunctionCall.
type OptChatCompletionRequestMessageFunctionCall struct {
	Value ChatCompletionRequestMessageFunctionCall
	Set   bool
}

// IsSet returns true if OptChatCompletionRequestMessageFunctionCall was set.
func (o OptChatCompletionRequestMessageFunctionCall) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptChatCompletionRequestMessageFunctionCall) Reset() {
	var v ChatCompletionRequestMessageFunctionCall
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptChatCompletionRequestMessageFunctionCall) SetTo(v ChatCompletionRequestMessageFunctionCall) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptChatCompletionRequestMessageFunctionCall) Get() (v ChatCompletionRequestMessageFunctionCall, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptChatCompletionRequestMessageFunctionCall) Or(d ChatCompletionRequestMessageFunctionCall) ChatCompletionRequestMessageFunctionCall {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptChatCompletionResponseMessageFunctionCall returns new OptChatCompletionResponseMessageFunctionCall with value set to v.
func NewOptChatCompletionResponseMessageFunctionCall(v ChatCompletionResponseMessageFunctionCall) OptChatCompletionResponseMessageFunctionCall {
	return OptChatCompletionResponseMessageFunctionCall{
		Value: v,
		Set:   true,
	}
}

// OptChatCompletionResponseMessageFunctionCall is optional ChatCompletionResponseMessageFunctionCall.
type OptChatCompletionResponseMessageFunctionCall struct {
	Value ChatCompletionResponseMessageFunctionCall
	Set   bool
}

// IsSet returns true if OptChatCompletionResponseMessageFunctionCall was set.
func (o OptChatCompletionResponseMessageFunctionCall) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptChatCompletionResponseMessageFunctionCall) Reset() {
	var v ChatCompletionResponseMessageFunctionCall
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptChatCompletionResponseMessageFunctionCall) SetTo(v ChatCompletionResponseMessageFunctionCall) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptChatCompletionResponseMessageFunctionCall) Get() (v ChatCompletionResponseMessageFunctionCall, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptChatCompletionResponseMessageFunctionCall) Or(d ChatCompletionResponseMessageFunctionCall) ChatCompletionResponseMessageFunctionCall {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCompletionTokensDetails returns new OptCompletionTokensDetails with value set to v.
func NewOptCompletionTokensDetails(v CompletionTokensDetails) OptCompletionTokensDetails {
	return OptCompletionTokensDetails{
		Value: v,
		Set:   true,
	}
}

// OptCompletionTokensDetails is optional CompletionTokensDetails.
type OptCompletionTokensDetails struct {
	Value CompletionTokensDetails
	Set   bool
}

// IsSet returns true if OptCompletionTokensDetails was set.
func (o OptCompletionTokensDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCompletionTokensDetails) Reset() {
	var v CompletionTokensDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCompletionTokensDetails) SetTo(v CompletionTokensDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCompletionTokensDetails) Get() (v CompletionTokensDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCompletionTokensDetails) Or(d CompletionTokensDetails) CompletionTokensDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCompletionUsage returns new OptCompletionUsage with value set to v.
func NewOptCompletionUsage(v CompletionUsage) OptCompletionUsage {
	return OptCompletionUsage{
		Value: v,
		Set:   true,
	}
}

// OptCompletionUsage is optional CompletionUsage.
type OptCompletionUsage struct {
	Value CompletionUsage
	Set   bool
}

// IsSet returns true if OptCompletionUsage was set.
func (o OptCompletionUsage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCompletionUsage) Reset() {
	var v CompletionUsage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCompletionUsage) SetTo(v CompletionUsage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCompletionUsage) Get() (v CompletionUsage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCompletionUsage) Or(d CompletionUsage) CompletionUsage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateChatCompletionRequestLogitBias returns new OptCreateChatCompletionRequestLogitBias with value set to v.
func NewOptCreateChatCompletionRequestLogitBias(v CreateChatCompletionRequestLogitBias) OptCreateChatCompletionRequestLogitBias {
	return OptCreateChatCompletionRequestLogitBias{
		Value: v,
		Set:   true,
	}
}

// OptCreateChatCompletionRequestLogitBias is optional CreateChatCompletionRequestLogitBias.
type OptCreateChatCompletionRequestLogitBias struct {
	Value CreateChatCompletionRequestLogitBias
	Set   bool
}

// IsSet returns true if OptCreateChatCompletionRequestLogitBias was set.
func (o OptCreateChatCompletionRequestLogitBias) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateChatCompletionRequestLogitBias) Reset() {
	var v CreateChatCompletionRequestLogitBias
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateChatCompletionRequestLogitBias) SetTo(v CreateChatCompletionRequestLogitBias) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateChatCompletionRequestLogitBias) Get() (v CreateChatCompletionRequestLogitBias, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateChatCompletionRequestLogitBias) Or(d CreateChatCompletionRequestLogitBias) CreateChatCompletionRequestLogitBias {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateChatCompletionRequestStop returns new OptCreateChatCompletionRequestStop with value set to v.
func NewOptCreateChatCompletionRequestStop(v CreateChatCompletionRequestStop) OptCreateChatCompletionRequestStop {
	return OptCreateChatCompletionRequestStop{
		Value: v,
		Set:   true,
	}
}

// OptCreateChatCompletionRequestStop is optional CreateChatCompletionRequestStop.
type OptCreateChatCompletionRequestStop struct {
	Value CreateChatCompletionRequestStop
	Set   bool
}

// IsSet returns true if OptCreateChatCompletionRequestStop was set.
func (o OptCreateChatCompletionRequestStop) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateChatCompletionRequestStop) Reset() {
	var v CreateChatCompletionRequestStop
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateChatCompletionRequestStop) SetTo(v CreateChatCompletionRequestStop) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateChatCompletionRequestStop) Get() (v CreateChatCompletionRequestStop, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateChatCompletionRequestStop) Or(d CreateChatCompletionRequestStop) CreateChatCompletionRequestStop {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateCompletionRequestLogitBias returns new OptCreateCompletionRequestLogitBias with value set to v.
func NewOptCreateCompletionRequestLogitBias(v CreateCompletionRequestLogitBias) OptCreateCompletionRequestLogitBias {
	return OptCreateCompletionRequestLogitBias{
		Value: v,
		Set:   true,
	}
}

// OptCreateCompletionRequestLogitBias is optional CreateCompletionRequestLogitBias.
type OptCreateCompletionRequestLogitBias struct {
	Value CreateCompletionRequestLogitBias
	Set   bool
}

// IsSet returns true if OptCreateCompletionRequestLogitBias was set.
func (o OptCreateCompletionRequestLogitBias) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateCompletionRequestLogitBias) Reset() {
	var v CreateCompletionRequestLogitBias
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateCompletionRequestLogitBias) SetTo(v CreateCompletionRequestLogitBias) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateCompletionRequestLogitBias) Get() (v CreateCompletionRequestLogitBias, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateCompletionRequestLogitBias) Or(d CreateCompletionRequestLogitBias) CreateCompletionRequestLogitBias {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateCompletionRequestStop returns new OptCreateCompletionRequestStop with value set to v.
func NewOptCreateCompletionRequestStop(v CreateCompletionRequestStop) OptCreateCompletionRequestStop {
	return OptCreateCompletionRequestStop{
		Value: v,
		Set:   true,
	}
}

// OptCreateCompletionRequestStop is optional CreateCompletionRequestStop.
type OptCreateCompletionRequestStop struct {
	Value CreateCompletionRequestStop
	Set   bool
}

// IsSet returns true if OptCreateCompletionRequestStop was set.
func (o OptCreateCompletionRequestStop) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateCompletionRequestStop) Reset() {
	var v CreateCompletionRequestStop
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateCompletionRequestStop) SetTo(v CreateCompletionRequestStop) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateCompletionRequestStop) Get() (v CreateCompletionRequestStop, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateCompletionRequestStop) Or(d CreateCompletionRequestStop) CreateCompletionRequestStop {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilChatCompletionChoiceLogprobs returns new OptNilChatCompletionChoiceLogprobs with value set to v.
func NewOptNilChatCompletionChoiceLogprobs(v ChatCompletionChoiceLogprobs) OptNilChatCompletionChoiceLogprobs {
	return OptNilChatCompletionChoiceLogprobs{
		Value: v,
		Set:   true,
	}
}

// OptNilChatCompletionChoiceLogprobs is optional nullable ChatCompletionChoiceLogprobs.
type OptNilChatCompletionChoiceLogprobs struct {
	Value ChatCompletionChoiceLogprobs
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilChatCompletionChoiceLogprobs was set.
func (o OptNilChatCompletionChoiceLogprobs) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilChatCompletionChoiceLogprobs) Reset() {
	var v ChatCompletionChoiceLogprobs
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilChatCompletionChoiceLogprobs) SetTo(v ChatCompletionChoiceLogprobs) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilChatCompletionChoiceLogprobs) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilChatCompletionChoiceLogprobs) SetToNull() {
	o.Set = true
	o.Null = true
	var v ChatCompletionChoiceLogprobs
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilChatCompletionChoiceLogprobs) Get() (v ChatCompletionChoiceLogprobs, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilChatCompletionChoiceLogprobs) Or(d ChatCompletionChoiceLogprobs) ChatCompletionChoiceLogprobs {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilChatCompletionTokenLogprobArray returns new OptNilChatCompletionTokenLogprobArray with value set to v.
func NewOptNilChatCompletionTokenLogprobArray(v []ChatCompletionTokenLogprob) OptNilChatCompletionTokenLogprobArray {
	return OptNilChatCompletionTokenLogprobArray{
		Value: v,
		Set:   true,
	}
}

// OptNilChatCompletionTokenLogprobArray is optional nullable []ChatCompletionTokenLogprob.
type OptNilChatCompletionTokenLogprobArray struct {
	Value []ChatCompletionTokenLogprob
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilChatCompletionTokenLogprobArray was set.
func (o OptNilChatCompletionTokenLogprobArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilChatCompletionTokenLogprobArray) Reset() {
	var v []ChatCompletionTokenLogprob
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilChatCompletionTokenLogprobArray) SetTo(v []ChatCompletionTokenLogprob) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilChatCompletionTokenLogprobArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilChatCompletionTokenLogprobArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ChatCompletionTokenLogprob
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilChatCompletionTokenLogprobArray) Get() (v []ChatCompletionTokenLogprob, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilChatCompletionTokenLogprobArray) Or(d []ChatCompletionTokenLogprob) []ChatCompletionTokenLogprob {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCompletionChoiceLogprobs returns new OptNilCompletionChoiceLogprobs with value set to v.
func NewOptNilCompletionChoiceLogprobs(v CompletionChoiceLogprobs) OptNilCompletionChoiceLogprobs {
	return OptNilCompletionChoiceLogprobs{
		Value: v,
		Set:   true,
	}
}

// OptNilCompletionChoiceLogprobs is optional nullable CompletionChoiceLogprobs.
type OptNilCompletionChoiceLogprobs struct {
	Value CompletionChoiceLogprobs
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCompletionChoiceLogprobs was set.
func (o OptNilCompletionChoiceLogprobs) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCompletionChoiceLogprobs) Reset() {
	var v CompletionChoiceLogprobs
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCompletionChoiceLogprobs) SetTo(v CompletionChoiceLogprobs) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCompletionChoiceLogprobs) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCompletionChoiceLogprobs) SetToNull() {
	o.Set = true
	o.Null = true
	var v CompletionChoiceLogprobs
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCompletionChoiceLogprobs) Get() (v CompletionChoiceLogprobs, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCompletionChoiceLogprobs) Or(d CompletionChoiceLogprobs) CompletionChoiceLogprobs {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt returns new OptNilInt with value set to v.
func NewOptNilInt(v int) OptNilInt {
	return OptNilInt{
		Value: v,
		Set:   true,
	}
}

// OptNilInt is optional nullable int.
type OptNilInt struct {
	Value int
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt was set.
func (o OptNilInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt) SetTo(v int) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt) SetToNull() {
	o.Set = true
	o.Null = true
	var v int
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPromptTokensDetails returns new OptPromptTokensDetails with value set to v.
func NewOptPromptTokensDetails(v PromptTokensDetails) OptPromptTokensDetails {
	return OptPromptTokensDetails{
		Value: v,
		Set:   true,
	}
}

// OptPromptTokensDetails is optional PromptTokensDetails.
type OptPromptTokensDetails struct {
	Value PromptTokensDetails
	Set   bool
}

// IsSet returns true if OptPromptTokensDetails was set.
func (o OptPromptTokensDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPromptTokensDetails) Reset() {
	var v PromptTokensDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPromptTokensDetails) SetTo(v PromptTokensDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPromptTokensDetails) Get() (v PromptTokensDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPromptTokensDetails) Or(d PromptTokensDetails) PromptTokensDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PromptTokensDetails
type PromptTokensDetails struct {
	CachedTokens OptInt `json:"cached_tokens"`
	AudioTokens  OptInt `json:"audio_tokens"`
}

// GetCachedTokens returns the value of CachedTokens.
func (s *PromptTokensDetails) GetCachedTokens() OptInt {
	return s.CachedTokens
}

// GetAudioTokens returns the value of AudioTokens.
func (s *PromptTokensDetails) GetAudioTokens() OptInt {
	return s.AudioTokens
}

// SetCachedTokens sets the value of CachedTokens.
func (s *PromptTokensDetails) SetCachedTokens(val OptInt) {
	s.CachedTokens = val
}

// SetAudioTokens sets the value of AudioTokens.
func (s *PromptTokensDetails) SetAudioTokens(val OptInt) {
	s.AudioTokens = val
}
