// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// RetrieveModelParams is parameters of retrieveModel operation.
type RetrieveModelParams struct {
	// The ID of the model to use for this request.
	Model string
}

func unpackRetrieveModelParams(packed middleware.Parameters) (params RetrieveModelParams) {
	{
		key := middleware.ParameterKey{
			Name: "model",
			In:   "path",
		}
		params.Model = packed[key].(string)
	}
	return params
}

func decodeRetrieveModelParams(args [1]string, argsEscaped bool, r *http.Request) (params RetrieveModelParams, _ error) {
	// Decode path: model.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "model",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Model = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "model",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
