// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateChatCompletionOperation OperationName = "CreateChatCompletion"
	CreateCompletionOperation     OperationName = "CreateCompletion"
	ListModelsOperation           OperationName = "ListModels"
	RetrieveModelOperation        OperationName = "RetrieveModel"
)
