name: PR Auto-merge

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run tests
        uses: takumi3488/mygha/go/test@67701e089671fc5fd1401c1a9b0d48e8b68fc644 # main

